# Generated by Django 3.0.4 on 2021-03-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electra', '0002_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(default='img1.jpg', upload_to='electra/images'),
        ),
    ]
