# Generated by Django 3.0.4 on 2021-03-19 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electra', '0004_point'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Point',
        ),
    ]
