# Generated by Django 3.0.4 on 2021-03-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electra', '0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='img',
            field=models.ImageField(default='img1.jpg', upload_to='electra/images'),
        ),
    ]
