# Generated by Django 3.0.4 on 2021-03-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electra', '0009_remove_response_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
