# Generated by Django 3.0.4 on 2021-03-27 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electra', '0010_response_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='submit_time',
        ),
    ]
