# Generated by Django 3.0.4 on 2021-03-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electra', '0011_remove_profile_submit_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='curr_round',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.TextField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRW6X2lldt_gy2tcbXCKBbKWNVBpH-f1Mcjsw&usqp=CAU'),
        ),
    ]
